name: Nanotech Inc.
favicon: null
layout_spectrum: 0.80704
typography_spectrum: 0.48137000342831016
title: Nanotidamond Grading Technology
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.30776263936422765
  lightness: 0.9463786149863154
  saturation: 0.05203397385776043
  rhythmicContrast: 0.40581258828751743
purpose: []
